# Generated by Django 5.0.1 on 2024-02-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkanalysis',
            name='article_authors',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='linkanalysis',
            name='article_header',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='linkanalysis',
            name='article_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='linkanalysis',
            name='article_publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
