# Generated by Django 5.0.1 on 2024-02-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_linkanalysis_article_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkanalysis',
            name='article_authors_community_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='linkanalysis',
            name='article_image_community_notes',
            field=models.URLField(blank=True),
        ),
    ]
